import random

def get_graduation_quote():
    quotes = [
        "You survived CSE. That's basically a superpower.",
        "May your merge conflicts be few and your caffeine plentiful.",
        "Real programmers don't graduate — they just get better error messages.",
        "Congrats! You now qualify for jobs that require 5+ years experience for entry level.",
        "Remember: If it compiles on the first try, something is deeply wrong.",
        "Your degree is now officially production-ready. Unlike most code.",
        "You didn’t just earn a degree—you earned +10 endurance, +15 debugging, and +20 Googling."
        "You now have a degree and still no idea why your code works.",
        "Your debugging skill is now your personality.",
        "May your future be as bug-free as your final year project pretended to be.",
        "Congrats! You unlocked the 'Professional Keyboard Smasher' achievement.",
        "Your degree: 20% knowledge, 80% googling.",
        "Remember: You are not stuck. You're just on a recursive break.",
        "You survived CSE. Therapy is now super effective.",
        "In the real world, semicolons matter even more.",
        "You now speak at least two languages: English and StackOverflow.",
        "Your code is now eligible for veteran pension benefits.",
        "Real life has no Ctrl+Z. Good luck.",
        "Welcome to adulthood, where debugging is done emotionally.",
        "Your GPA doesn’t matter. Your GitHub streak does.",
        "May your job offers be frequent and your Jira tickets few.",
        "You now qualify to yell 'It works on my machine!' professionally.",
        "Your salary now depends on whether or not you included a semicolon.",
        "Congratulations, you're now a Senior Copy-Paste Engineer.",
        "Your student loan interest rate compiles faster than your code.",
        "You are now allowed to judge people's text editors.",
        "You graduated! Time to lose the will to update your LinkedIn.",
        "Your diploma is the final patch note.",
        "You're now certified to explain things no one asked about.",
        "Your brain has been successfully garbage-collected.",
        "You made it! Now go break production responsibly.",
        "You now understand that 'temporary fix' means 'permanent feature'.",
        "You can finally uninstall all your university stress dependencies.",
        "Your new job will be turning coffee into slightly better coffee.",
        "Remember: Every great programmer was once as confused as you are.",
        "You're no longer a student. You're a bug hunter.",
        "Job interviews: the final boss of your degree.",
        "May your Git pulls never contain surprises.",
        "If you ever feel useless, remember: someone wrote the HTML for MySpace.",
        "You can now architect solutions that you still don’t fully understand.",
        "Real-world code reviews will now feel like performance evaluations.",
        "Your debugging rubber duck will miss you.",
        "You now qualify to understand jokes about Kubernetes you still don’t get.",
        "Congrats! You survived infinite loops and finite patience.",
        "Your degree prepared you for everything except printer errors.",
        "You earned a certificate in professional Googling.",
        "You are now legally allowed to say 'Actually, it’s more complicated…'.",
        "Your brain now supports multithreading… emotionally.",
        "Goodbye university, hello 1000 new browser tabs.",
        "You can now reject job offers that ask for 10 years of React.",
        "Your code is no longer marked—it is judged.",
        "You have upgraded from student to junior-level chaos engine.",
        "Your coffee intake is now a business expense.",
        "You can finally stop pretending you like group projects.",
        "You escaped tutorial hell. Welcome to sprint planning hell.",
        "Congratulations! Time to explain your major to relatives forever.",
        "You passed! Your stress module has been deprecated (but still runs).",
        "Your future is bright—and slightly over-engineered.",
        "You now have a degree in making things complicated.",
        "You no longer get marked; you get monitored.",
        "Your new job title: 'Button-clicking problem solver'.",
        "You are now fluent in 1 programming language and 7 existential crises.",
        "Your code works? Ship it before it stops.",
        "You now qualify to say 'This tech is outdated' once a month.",
        "Your brain's RAM usage is now optimal. Just don't restart.",
        "You survived on caffeine, stress, and vibes alone.",
        "You have leveled up in 'Pretending to Know Things'.",
        "You’ve graduated! Git blame someone else now.",
        "You're now a licensed algorithm wrangler.",
        "Remember: A clean desk is a sign of a broken computer.",
        "You now have a degree. No more excuses — it's time to procrastinate professionally.",
        "Graduation unlocked! DLC: Taxes.",
        "You now know that computers are just drama queens with keyboards.",
        "Your future bugs will be paid bugs.",
        "Never forget: The cloud is just someone else's computer.",
        "You're now ready to join meetings that could've been emails.",
        "Your brain is done compiling your education.",
        "You survived lectures that were basically patch notes.",
        "Your degree is a fancy way of saying 'knows where the power button is'.",
        "Congrats! You’ve officially mastered the art of overthinking.",
        "Your code has finally graduated from spaghetti to lasagna.",
        "You now understand recursion because... wait, do you?",
        "Your code is like your future: undocumented but promising.",
        "May your algorithms be efficient and your deadlines lenient.",
        "You finished your degree! Time to update your dev environment (your life).",
        "You can now understand Git conflicts and family conflicts.",
        "Your degree is the ultimate pull request. Approved!",
        "You didn't just graduate—you successfully avoided a segmentation fault.",
        "Your debugging skills are now endorsed by sheer trauma.",
        "You survived 4 years of code. Production will be… interesting.",
        "You now qualify to use dark mode 24/7.",
        "Years of study, and you still fear the infinite spinner.",
        "Your compiler is proud of you. Sometimes.",
        "Welcome to life after graduation: version 1.0. Bugs expected.",
        "You're now free to optimize your life like your code: barely.",
        "Your code is still bad, but now you get paid for it.",
        "You didn’t pass your degree. You outlasted it.",
        "Welcome to the workforce! A land ruled by Jira and broken promises.",
        "You went from ‘Hello World’ to ‘Why is this happening’.",
        "Good news: No more exams. Bad news: Now there are deadlines.",
        "You graduated! StackOverflow will continue to support you in this time.",
        "If your life had unit tests, graduation would've failed at least 3.",
        "You're now a full-time 'Why doesn't this work?' specialist.",
        "Congratulations! You're now an expert in pretending you know git rebase.",
        "Your degree is complete; your imposter syndrome update is pending."
    ]

    return random.choice(quotes)

if __name__ == "__main__":
    print("\n🎓 Graduation Quote Generator 🎓")
    print(get_graduation_quote())
    print()